SEARCH_DIR("/lib/aarch64-linux-gnu/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/aarch64-linux-gnu/14/")
SEARCH_DIR("./")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_pl/pl_ExCompress/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_pl/pl_Abbrevia/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_lz/lz_CustomDrawnDsg/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseEnginesPlus/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_lz/lz_Printers/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseEngines/lib/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseDebuggerIntf/lib/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseCodeTools/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/ca_libQT5/lib/aarch64-linux/qt5/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/packager/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libusb/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libpng/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk1/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ldap/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/httpd22/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-fpterm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-stl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/xforms/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-ebnf/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-jsonschema/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/a52/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/svgalib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/regexpr/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/oggvorbis/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/symbolic/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/imlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libnettle/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gst/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-extra/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/dbus/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fv/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/zorba/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/sdl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/webidl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/tcl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/numlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-mustache/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ptckvm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/lua/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/bzip2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/openal/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libxml2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ibase/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/mysql/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gmp/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-yaml/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libfontconfig/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-net/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-passrc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fftw/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-js/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ptc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libgd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/vcl-compat/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ncurses/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/newt/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pastojs/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gdbint/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-registry/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rsvg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/graph/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gdbm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libsndfile/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-unicode/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/dblib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/uuid/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/tplylib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libsee/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/openssl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/cairo/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/odbc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libpipewire/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-res/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-sound/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/modplug/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-css/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pxlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ggi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fastcgi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pas2js/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-async/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/dts/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pthreads/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-extra/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/testinsight/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libcups/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/hash/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/bfd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/aspell/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libtar/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/imagemagick/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/mariadb/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/unzip/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-md/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pcap/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/cdrom/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libenet/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gitlab/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libpcre/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libffi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/firebird/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/syslog/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-wit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/oracle/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libmagic/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/redis/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/sqlite/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-openapi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/opengl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libmicrohttpd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/hermes/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-pdf/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/zlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-hash/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/wasm-job/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-console/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/odata/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-process/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-syntax/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gnutls/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/utmp/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/opengles/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-sdo/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libcurl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/users/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fpmkunit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fpindexer/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/iconvenc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/jni/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gnome1/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/chm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-db/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/proj4/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/postgres/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libvlc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libjack/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/mad/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libgc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/httpd24/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fpgtk/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fppkg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/bin/aarch64-linux/")
INPUT(
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/cprt0.o
/lib/aarch64-linux-gnu/crti.o
/usr/lib/gcc/aarch64-linux-gnu/14/crtbegin.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/pibackup.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/pibackup.or
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/system.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/lnfodwrf.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/exeinfo.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/strings.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/fpintres.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/objpas.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/cthreads.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unix.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/qtfix.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/interfaces.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/forms.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/dialogs.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/rkutils.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/unit1.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/exethread.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/usersetup.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/uitheme.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/unit2.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/linux.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/baseunix.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unixtype.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/initc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/dl.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/ctypes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/cwstring.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/interfacebase.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/dynlibs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unixcp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/types.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/classes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/sysutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/math.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpimage.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclproc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lcltype.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lmessages.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclplatformdef.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/intfgraphics.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/themes.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsreferences.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutf8.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/integerlist.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutilities.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazloggerbase.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/graphtype.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/graphmath.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazversion.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/errors.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/sysconst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unixutil.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/typinfo.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/rtlconsts.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/sortbase.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/avl_tree.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazfileutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazmethodlist.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutf16.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laztracer.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclstrconsts.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutilsstrconsts.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/fpcadds.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/strutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazclasses.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/system.uitypes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadbmp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritebmp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/bmpcomn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadpng.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritepng.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadtiff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritetiff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fptiffcmn.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclversion.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/icnstypes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpimgcmn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/pngcomn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zstream.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zbase.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/gzio.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/hash/crc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zdeflate.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zinflate.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/trees.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/adler.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/infblock.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/infutil.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/infcodes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/inftrees.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/inffast.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpcolorspace.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/graphics.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclintf.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/contnrs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpcanvas.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadpnm.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritepnm.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadjpeg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritejpeg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadtga.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritetga.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadgif.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lresources.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclrescache.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/clipping.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/jpegcomn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jpeglib.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdapimin.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdatasrc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdapistd.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jmorecfg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdeferr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jinclude.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jerror.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jmemmgr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmarker.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdinput.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcomapi.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jmemnobs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmaster.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdcolor.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdsample.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdpostct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jddctmgr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdphuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdhuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdcoefct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmainct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jquant1.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jquant2.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmerge.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctfst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctint.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctflt.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctred.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcapistd.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcapimin.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdatadst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcparam.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcinit.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcmarker.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcphuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jchuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcmaster.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jccolor.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcsample.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcprepct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcdctmgr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jccoefct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcmainct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jfdctint.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jfdctfst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jfdctflt.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/targacmn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/variants.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazconfigstorage.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/dynqueue.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/varutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/avglvltree.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazstringutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazdbglog.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/syncobjs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/system.timespan.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pthreads/pthreads.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/fileutil.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/utf8process.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazsysutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/maps.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/tmschema.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/fgl.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/masks.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-process/process.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-process/pipes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/termio.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5int.o
/usr/local/codetyphon/typhon/components/ca_libQT5/lib/aarch64-linux/qt5/qt5.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclmessageglue.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/controls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/extctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/stdctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/graphutil.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5x11dummywidget.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5proc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclclasses.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/custapp.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/menus.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/customtimer.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/actnlist.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/clipbrd.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/helpintfs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/imglist.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/singleinstance.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wslclclasses.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpimgcanv.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fppixlcanv.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/pixtools.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/ellipses.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/polygonfilltools.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsimglist.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsproc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsfactory.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/propertystorage.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/rttiutils.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsmenus.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/chm/fasthtmlparser.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wscontrols.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsforms.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/popupnotifier.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/textstrings.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/extendedstrings.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsstdctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsextctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/buttons.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/buttonpanel.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/dialogres.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/comctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/imagelistcache.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsbuttons.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/toolwin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wscomctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wstoolwin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsdialogs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/taskdlgemulation.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/dateutils.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lazcanvas.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lazregions.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5objects.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/x.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/xlib.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/xkb.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/xkblib.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5caret.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5themes.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsfactory.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5widgets.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5systemtrayicon.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/xi.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5private.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/calendar.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/spin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/grids.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/checklst.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/rubberband.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/pairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wscalendar.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsspin.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/htmldefs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/maskedit.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/dynamicarray.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlcfg.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lcsvutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazfilecache.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_dom.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlread.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlwrite.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/uriparser.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsgrids.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wschecklst.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsdesigner.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wspairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsbuttons.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wscalendar.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wschecklst.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wscomctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wscontrols.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsdialogs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsextctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsforms.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsmenus.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wspairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsspin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsstdctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsgrids.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/qt5/qt5wsdesigner.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/extdlgs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/calcform.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsextdlgs.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/zstd.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/inifiles.o
/home/pi/git/pibackup_neu/source/lib/aarch64-linux/excludeparser.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/fpjson.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/jsonparser.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/jsonscanner.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/jsonreader.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/htmlview.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HTMLUn2.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlGlobals.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/htmlmisc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/messages.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/UrlConn.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/URLSubs.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlFonts.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlBuffer.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlImages.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlPrinter.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/vwPrint.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/ReadHTML.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HTMLSubs.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/StyleTypes.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/StyleUn.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/printers.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/base64.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/MetaFilePrinter.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HTMLGif2.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlSymb.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/BuffConv.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/BuffConvArrays.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/htmlgif1.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HtmlCaches.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/DitherUnit.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/StylePars.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/HSLUtils.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/Htmlsbs1.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_HtmlViewer/lib/aarch64-linux/qt5/framview.o
)
INPUT(
-lpthread
-ldl
-lQt5Pas
-lX11
-lzstd
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/aarch64-linux-gnu/14/crtend.o
/lib/aarch64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
